### PR TITLE
Added joy_to_twist node

### PR DESCRIPTION
**Pull request by CBJamo**

### CODE REVIEW

**Comment by cottsay** [comment]
Can you rebase this from `master` to pull in the `.travis.yml` for compile testing?

**Comment by CBJamo** [comment]
Done

**Comment by cottsay** [comment]
run `git rebase upstream/master` so it doesn't have an extra merge commit. You'll need to force-push to your repo, but it will merge cleanly with mine.

**Comment by cottsay** [comment]
Yes, wonderful. Thanks.

**Pull request merged**
